POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "This is a test chirp"
}

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "This is a test chirp that is too long and should be rejected because it is over 140 characters, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "This is a test chirp with profanity, kerfuffle"
}

###

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "This is a test chirp with profanity but should be accepted, sharbert!"
}
